import type {
  AnimalType,
  Sex,
  AgeGroup,
  Size,
  CoatLength,
  EnergyLevel,
} from "../../src/db/schema/posts-schema";

if (!process.env.SEED_USER_PASSWORD) {
  throw new Error(
    "SEED_USER_PASSWORD not found in environment variables. Add it to your .env/.env.development file.",
  );
}

export const SEED_PASSWORD = process.env.SEED_USER_PASSWORD;

export type SeedUser = {
  id: string;
  name: string;
  email: string;
};

export const seedUsers: SeedUser[] = [
  { id: "seed_user_owner_us", name: "Jamie Rivera", email: "owner-us@seed.pawsitiveadopting.test" },
  { id: "seed_user_owner_ar", name: "Martina Gomez", email: "owner-ar@seed.pawsitiveadopting.test" },
  { id: "seed_user_owner_cl", name: "Tomas Reyes", email: "owner-cl@seed.pawsitiveadopting.test" },
  { id: "seed_user_owner_mx", name: "Sofia Hernandez", email: "owner-mx@seed.pawsitiveadopting.test" },
  { id: "seed_user_owner_es", name: "Lucia Fernandez", email: "owner-es@seed.pawsitiveadopting.test" },
  { id: "seed_user_owner_ca", name: "Liam Tremblay", email: "owner-ca@seed.pawsitiveadopting.test" },
  { id: "seed_user_adopter", name: "Alex Chen", email: "adopter@seed.pawsitiveadopting.test" },
];

export type SeedAssociation = {
  id: string;
  name: string;
  slug: string;
  ownerId: string;
  logo?: string;
  description?: string;
  city?: string;
  state?: string;
  country?: string;
};

export const seedAssociations: SeedAssociation[] = [
  {
    id: "seed_assoc_us",
    name: "Happy Paws Rescue",
    slug: "happy-paws-rescue-seed",
    ownerId: "seed_user_owner_us",
    logo: "https://images.unsplash.com/photo-1450778869180-41d0601e046e?w=400",
    description:
      "A volunteer-run rescue dedicated to finding loving homes for dogs and cats across the Pacific Northwest.",
    city: "Portland",
    state: "Oregon",
    country: "United States",
  },
  {
    id: "seed_assoc_ar",
    name: "Rescate Patagonia",
    slug: "rescate-patagonia-seed",
    ownerId: "seed_user_owner_ar",
    description:
      "Rescatamos y rehabilitamos animales en situación de calle en la Patagonia argentina.",
    city: "Bariloche",
    state: "Río Negro",
    country: "Argentina",
  },
  {
    id: "seed_assoc_cl",
    name: "Huellitas del Sur",
    slug: "huellitas-del-sur-seed",
    ownerId: "seed_user_owner_cl",
    description:
      "Organización sin fines de lucro enfocada en la adopción responsable de perros y gatos en el sur de Chile.",
    city: "Puerto Montt",
    state: "Los Lagos",
    country: "Chile",
  },
  {
    id: "seed_assoc_mx",
    name: "Patitas Mexico",
    slug: "patitas-mexico-seed",
    ownerId: "seed_user_owner_mx",
    logo: "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=400",
    description:
      "Refugio comunitario dedicado al rescate y adopcion responsable de perros y gatos en la Ciudad de Mexico.",
    city: "Ciudad de Mexico",
    state: "CDMX",
    country: "Mexico",
  },
  {
    id: "seed_assoc_es",
    name: "Adopta un Amigo",
    slug: "adopta-un-amigo-seed",
    ownerId: "seed_user_owner_es",
    description:
      "Protectora sin animo de lucro que trabaja por el bienestar y la adopcion de animales abandonados en Madrid.",
    city: "Madrid",
    state: "Madrid",
    country: "Spain",
  },
  {
    id: "seed_assoc_ca",
    name: "Northern Paws Rescue",
    slug: "northern-paws-rescue-seed",
    ownerId: "seed_user_owner_ca",
    logo: "https://images.unsplash.com/photo-1544568100-847a948585b9?w=400",
    description:
      "A foster-based rescue helping dogs and cats across Ontario find their forever homes.",
    city: "Toronto",
    state: "Ontario",
    country: "Canada",
  },
];

export type SeedPost = {
  associationId: string;
  animalType: AnimalType;
  name: string;
  description: string;
  city: string;
  state: string | null;
  country: string;
  latitude: number;
  longitude: number;
  breed: string;
  sex: Sex;
  ageGroup: AgeGroup;
  size: Size;
  coatLength: CoatLength;
  coatColorPrimary: string;
  temperamentTags: string[];
  goodWithKids: boolean;
  goodWithDogs: boolean;
  goodWithCats: boolean;
  goodInApartment: boolean;
  goodInHouse: boolean;
  goodInGarden: boolean;
  energyLevel: EnergyLevel;
  adoptionFee: string;
  imageUrl: string;
};

// AR (Bariloche) and CL (Puerto Varas) posts sit ~135km apart across the
// Argentina/Chile border, close enough that a radius search from one will
// surface the other unless "same country only" is enabled.
export const seedPosts: SeedPost[] = [
  // ---- US (Happy Paws Rescue) ----
  {
    associationId: "seed_assoc_us",
    animalType: "cat",
    name: "Sapphire",
    description:
      "Sapphire is a gorgeous 2-year-old Siamese cat with striking blue eyes. Vocal, intelligent, and very social.",
    city: "New York",
    state: "New York",
    country: "US",
    latitude: 40.7128,
    longitude: -74.006,
    breed: "Siamese",
    sex: "female",
    ageGroup: "young",
    size: "medium",
    coatLength: "short",
    coatColorPrimary: "cream",
    temperamentTags: ["vocal", "intelligent", "social"],
    goodWithKids: true,
    goodWithDogs: true,
    goodWithCats: true,
    goodInApartment: true,
    goodInHouse: true,
    goodInGarden: false,
    energyLevel: "high",
    adoptionFee: "150.00",
    imageUrl: "https://images.unsplash.com/photo-1513360371669-4adf3dd7dff8?w=800",
  },
  {
    associationId: "seed_assoc_us",
    animalType: "dog",
    name: "Buddy",
    description:
      "Buddy is a friendly 3-year-old Labrador mix who loves fetch and long walks in the park.",
    city: "Los Angeles",
    state: "California",
    country: "US",
    latitude: 34.0522,
    longitude: -118.2437,
    breed: "Labrador Mix",
    sex: "male",
    ageGroup: "adult",
    size: "large",
    coatLength: "short",
    coatColorPrimary: "golden",
    temperamentTags: ["friendly", "playful", "loyal"],
    goodWithKids: true,
    goodWithDogs: true,
    goodWithCats: false,
    goodInApartment: false,
    goodInHouse: true,
    goodInGarden: true,
    energyLevel: "high",
    adoptionFee: "120.00",
    imageUrl: "https://images.unsplash.com/photo-1552053831-71594a27632d?w=800",
  },
  {
    associationId: "seed_assoc_us",
    animalType: "cat",
    name: "Duchess",
    description:
      "Duchess is a stunning 6-year-old European Longhair with luxurious silver fur. Calm and dignified.",
    city: "San Francisco",
    state: "California",
    country: "US",
    latitude: 37.7749,
    longitude: -122.4194,
    breed: "European Longhair",
    sex: "female",
    ageGroup: "adult",
    size: "medium",
    coatLength: "long",
    coatColorPrimary: "silver",
    temperamentTags: ["calm", "regal", "affectionate"],
    goodWithKids: true,
    goodWithDogs: false,
    goodWithCats: true,
    goodInApartment: true,
    goodInHouse: true,
    goodInGarden: false,
    energyLevel: "low",
    adoptionFee: "130.00",
    imageUrl: "https://images.unsplash.com/photo-1595433707802-6b2626ef1c91?w=800",
  },
  {
    associationId: "seed_assoc_us",
    animalType: "dog",
    name: "Charlie",
    description:
      "Charlie is a gentle 5-month-old Ragdoll-tempered puppy who loves to cuddle and follow people around.",
    city: "Portland",
    state: "Oregon",
    country: "US",
    latitude: 45.5152,
    longitude: -122.6784,
    breed: "Poodle Mix",
    sex: "male",
    ageGroup: "puppy/kitten",
    size: "small",
    coatLength: "long",
    coatColorPrimary: "cream",
    temperamentTags: ["gentle", "cuddly", "relaxed"],
    goodWithKids: true,
    goodWithDogs: true,
    goodWithCats: true,
    goodInApartment: true,
    goodInHouse: true,
    goodInGarden: false,
    energyLevel: "low",
    adoptionFee: "180.00",
    imageUrl: "https://images.unsplash.com/photo-1543852786-1cf6624b9987?w=800",
  },
  {
    associationId: "seed_assoc_us",
    animalType: "cat",
    name: "Milo",
    description:
      "Milo is a curious 4-year-old tabby who loves sunny windowsills and chasing laser pointers.",
    city: "Seattle",
    state: "Washington",
    country: "US",
    latitude: 47.6062,
    longitude: -122.3321,
    breed: "Domestic Shorthair",
    sex: "male",
    ageGroup: "adult",
    size: "medium",
    coatLength: "short",
    coatColorPrimary: "brown",
    temperamentTags: ["curious", "playful", "independent"],
    goodWithKids: true,
    goodWithDogs: false,
    goodWithCats: true,
    goodInApartment: true,
    goodInHouse: true,
    goodInGarden: false,
    energyLevel: "medium",
    adoptionFee: "110.00",
    imageUrl: "https://images.unsplash.com/photo-1533738363-b7f9aef128ce?w=800",
  },

  // ---- Argentina (Rescate Patagonia, Bariloche) ----
  {
    associationId: "seed_assoc_ar",
    animalType: "dog",
    name: "Rio",
    description:
      "Rio es un mestizo patagonico de 2 anos, muy activo y companero ideal para caminatas en la montana.",
    city: "San Carlos de Bariloche",
    state: "Rio Negro",
    country: "AR",
    latitude: -41.1335,
    longitude: -71.3103,
    breed: "Patagonian Mixed Breed",
    sex: "male",
    ageGroup: "young",
    size: "medium",
    coatLength: "medium",
    coatColorPrimary: "brown",
    temperamentTags: ["active", "loyal", "outdoorsy"],
    goodWithKids: true,
    goodWithDogs: true,
    goodWithCats: false,
    goodInApartment: false,
    goodInHouse: true,
    goodInGarden: true,
    energyLevel: "high",
    adoptionFee: "0.00",
    imageUrl: "https://images.unsplash.com/photo-1517849845537-4d257902861a?w=800",
  },
  {
    associationId: "seed_assoc_ar",
    animalType: "cat",
    name: "Nieve",
    description:
      "Nieve es una gata blanca de 1 ano, tranquila y carinosa, ideal para departamentos.",
    city: "San Carlos de Bariloche",
    state: "Rio Negro",
    country: "AR",
    latitude: -41.15,
    longitude: -71.32,
    breed: "Domestic Shorthair",
    sex: "female",
    ageGroup: "young",
    size: "small",
    coatLength: "short",
    coatColorPrimary: "white",
    temperamentTags: ["calm", "affectionate", "quiet"],
    goodWithKids: true,
    goodWithDogs: false,
    goodWithCats: true,
    goodInApartment: true,
    goodInHouse: true,
    goodInGarden: false,
    energyLevel: "low",
    adoptionFee: "0.00",
    imageUrl: "https://images.unsplash.com/photo-1478098711619-5ab0b478d6e6?w=800",
  },
  {
    associationId: "seed_assoc_ar",
    animalType: "dog",
    name: "Huesos",
    description:
      "Huesos es un adulto de 4 anos, tranquilo y bien entrenado, se lleva bien con otros perros.",
    city: "El Bolson",
    state: "Rio Negro",
    country: "AR",
    latitude: -41.9667,
    longitude: -71.5333,
    breed: "Collie Mix",
    sex: "male",
    ageGroup: "adult",
    size: "large",
    coatLength: "medium",
    coatColorPrimary: "black",
    temperamentTags: ["calm", "trained", "friendly"],
    goodWithKids: true,
    goodWithDogs: true,
    goodWithCats: true,
    goodInApartment: false,
    goodInHouse: true,
    goodInGarden: true,
    energyLevel: "medium",
    adoptionFee: "0.00",
    imageUrl: "https://images.unsplash.com/photo-1561037404-61cd46aa615b?w=800",
  },
  {
    associationId: "seed_assoc_ar",
    animalType: "cat",
    name: "Canela",
    description:
      "Canela es una gata de 2 anos, juguetona y muy sociable, se lleva bien con perros.",
    city: "San Carlos de Bariloche",
    state: "Rio Negro",
    country: "AR",
    latitude: -41.14,
    longitude: -71.31,
    breed: "Domestic Shorthair",
    sex: "female",
    ageGroup: "young",
    size: "small",
    coatLength: "short",
    coatColorPrimary: "orange",
    temperamentTags: ["playful", "sociable", "affectionate"],
    goodWithKids: true,
    goodWithDogs: true,
    goodWithCats: true,
    goodInApartment: true,
    goodInHouse: true,
    goodInGarden: false,
    energyLevel: "medium",
    adoptionFee: "0.00",
    imageUrl: "https://images.unsplash.com/photo-1592194996308-7b43878e84a6?w=800",
  },
  {
    associationId: "seed_assoc_ar",
    animalType: "dog",
    name: "Toby",
    description:
      "Toby es un cachorro de 5 meses, muy energico y curioso, ideal para una familia activa.",
    city: "El Bolson",
    state: "Rio Negro",
    country: "AR",
    latitude: -41.97,
    longitude: -71.53,
    breed: "Mixed Breed",
    sex: "male",
    ageGroup: "puppy/kitten",
    size: "medium",
    coatLength: "medium",
    coatColorPrimary: "black",
    temperamentTags: ["energetic", "curious", "playful"],
    goodWithKids: true,
    goodWithDogs: true,
    goodWithCats: false,
    goodInApartment: false,
    goodInHouse: true,
    goodInGarden: true,
    energyLevel: "high",
    adoptionFee: "0.00",
    imageUrl: "https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=800",
  },

  // ---- Chile (Huellitas del Sur, Puerto Varas) ----
  {
    associationId: "seed_assoc_cl",
    animalType: "cat",
    name: "Luna",
    description:
      "Luna es una gata de 3 anos, juguetona y curiosa, le encanta mirar por la ventana al lago.",
    city: "Puerto Varas",
    state: "Los Lagos",
    country: "CL",
    latitude: -41.3195,
    longitude: -72.9854,
    breed: "Domestic Shorthair",
    sex: "female",
    ageGroup: "adult",
    size: "small",
    coatLength: "short",
    coatColorPrimary: "orange",
    temperamentTags: ["playful", "curious", "vocal"],
    goodWithKids: true,
    goodWithDogs: true,
    goodWithCats: true,
    goodInApartment: true,
    goodInHouse: true,
    goodInGarden: false,
    energyLevel: "high",
    adoptionFee: "0.00",
    imageUrl: "https://images.unsplash.com/photo-1574158622682-e40e69881006?w=800",
  },
  {
    associationId: "seed_assoc_cl",
    animalType: "dog",
    name: "Cafe",
    description:
      "Cafe es un cachorro de 6 meses, energico y sociable, perfecto para una familia activa.",
    city: "Puerto Varas",
    state: "Los Lagos",
    country: "CL",
    latitude: -41.3,
    longitude: -73.0,
    breed: "Mixed Breed",
    sex: "male",
    ageGroup: "puppy/kitten",
    size: "medium",
    coatLength: "short",
    coatColorPrimary: "brown",
    temperamentTags: ["energetic", "sociable", "playful"],
    goodWithKids: true,
    goodWithDogs: true,
    goodWithCats: false,
    goodInApartment: false,
    goodInHouse: true,
    goodInGarden: true,
    energyLevel: "high",
    adoptionFee: "0.00",
    imageUrl: "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=800",
  },
  {
    associationId: "seed_assoc_cl",
    animalType: "cat",
    name: "Sombra",
    description:
      "Sombra es un gato senior de 8 anos, tranquilo, ideal para companero de lectura.",
    city: "Puerto Montt",
    state: "Los Lagos",
    country: "CL",
    latitude: -41.4693,
    longitude: -72.9424,
    breed: "Domestic Shorthair",
    sex: "male",
    ageGroup: "senior",
    size: "medium",
    coatLength: "short",
    coatColorPrimary: "black",
    temperamentTags: ["calm", "quiet", "gentle"],
    goodWithKids: true,
    goodWithDogs: false,
    goodWithCats: true,
    goodInApartment: true,
    goodInHouse: true,
    goodInGarden: false,
    energyLevel: "low",
    adoptionFee: "0.00",
    imageUrl: "https://images.unsplash.com/photo-1526336024174-e58f5cdd8e13?w=800",
  },
  {
    associationId: "seed_assoc_cl",
    animalType: "dog",
    name: "Kimun",
    description:
      "Kimun es un perro adulto de 3 anos, tranquilo y protector, disfruta de las caminatas cortas.",
    city: "Puerto Montt",
    state: "Los Lagos",
    country: "CL",
    latitude: -41.472,
    longitude: -72.94,
    breed: "Ovejero Mix",
    sex: "male",
    ageGroup: "adult",
    size: "large",
    coatLength: "medium",
    coatColorPrimary: "black",
    temperamentTags: ["calm", "protective", "loyal"],
    goodWithKids: true,
    goodWithDogs: true,
    goodWithCats: false,
    goodInApartment: false,
    goodInHouse: true,
    goodInGarden: true,
    energyLevel: "medium",
    adoptionFee: "0.00",
    imageUrl: "https://images.unsplash.com/photo-1518717758536-85ae29035b6d?w=800",
  },
  {
    associationId: "seed_assoc_cl",
    animalType: "cat",
    name: "Pandora",
    description:
      "Pandora es una gatita de 5 meses, muy juguetona y curiosa, se adapta rapido a nuevos hogares.",
    city: "Puerto Varas",
    state: "Los Lagos",
    country: "CL",
    latitude: -41.32,
    longitude: -72.98,
    breed: "Domestic Shorthair",
    sex: "female",
    ageGroup: "puppy/kitten",
    size: "small",
    coatLength: "short",
    coatColorPrimary: "cream",
    temperamentTags: ["playful", "curious", "affectionate"],
    goodWithKids: true,
    goodWithDogs: false,
    goodWithCats: true,
    goodInApartment: true,
    goodInHouse: true,
    goodInGarden: false,
    energyLevel: "high",
    adoptionFee: "0.00",
    imageUrl: "https://images.unsplash.com/photo-1573865526739-10659fec78a5?w=800",
  },

  // ---- Mexico (Patitas Mexico, Ciudad de Mexico) ----
  {
    associationId: "seed_assoc_mx",
    animalType: "dog",
    name: "Frijol",
    description:
      "Frijol es un perro adulto de 4 anos, jugueton y muy leal, perfecto para una familia con jardin.",
    city: "Ciudad de Mexico",
    state: "CDMX",
    country: "MX",
    latitude: 19.4326,
    longitude: -99.1332,
    breed: "Xoloitzcuintle Mix",
    sex: "male",
    ageGroup: "adult",
    size: "medium",
    coatLength: "hairless",
    coatColorPrimary: "black",
    temperamentTags: ["loyal", "playful", "friendly"],
    goodWithKids: true,
    goodWithDogs: true,
    goodWithCats: false,
    goodInApartment: false,
    goodInHouse: true,
    goodInGarden: true,
    energyLevel: "medium",
    adoptionFee: "0.00",
    imageUrl: "https://images.unsplash.com/photo-1517849845537-4d257902861a?w=800",
  },
  {
    associationId: "seed_assoc_mx",
    animalType: "cat",
    name: "Estrella",
    description:
      "Estrella es una gata de 1 ano, tranquila y carinosa, ideal para un departamento.",
    city: "Ciudad de Mexico",
    state: "CDMX",
    country: "MX",
    latitude: 19.43,
    longitude: -99.14,
    breed: "Domestic Shorthair",
    sex: "female",
    ageGroup: "young",
    size: "small",
    coatLength: "short",
    coatColorPrimary: "white",
    temperamentTags: ["calm", "affectionate", "quiet"],
    goodWithKids: true,
    goodWithDogs: false,
    goodWithCats: true,
    goodInApartment: true,
    goodInHouse: true,
    goodInGarden: false,
    energyLevel: "low",
    adoptionFee: "0.00",
    imageUrl: "https://images.unsplash.com/photo-1574158622682-e40e69881006?w=800",
  },
  {
    associationId: "seed_assoc_mx",
    animalType: "dog",
    name: "Pancho",
    description:
      "Pancho es un cachorro de 4 meses, muy energico, aun aprendiendo modales pero super carinoso.",
    city: "Guadalajara",
    state: "Jalisco",
    country: "MX",
    latitude: 20.6597,
    longitude: -103.3496,
    breed: "Mixed Breed",
    sex: "male",
    ageGroup: "puppy/kitten",
    size: "medium",
    coatLength: "short",
    coatColorPrimary: "brown",
    temperamentTags: ["energetic", "affectionate", "playful"],
    goodWithKids: true,
    goodWithDogs: true,
    goodWithCats: true,
    goodInApartment: false,
    goodInHouse: true,
    goodInGarden: true,
    energyLevel: "high",
    adoptionFee: "0.00",
    imageUrl: "https://images.unsplash.com/photo-1552053831-71594a27632d?w=800",
  },
  {
    associationId: "seed_assoc_mx",
    animalType: "cat",
    name: "Canela",
    description:
      "Canela es una gata senior de 9 anos, muy tranquila, busca un hogar calmado para sus ultimos anos.",
    city: "Ciudad de Mexico",
    state: "CDMX",
    country: "MX",
    latitude: 19.4,
    longitude: -99.15,
    breed: "Domestic Shorthair",
    sex: "female",
    ageGroup: "senior",
    size: "medium",
    coatLength: "short",
    coatColorPrimary: "orange",
    temperamentTags: ["calm", "gentle", "quiet"],
    goodWithKids: true,
    goodWithDogs: false,
    goodWithCats: true,
    goodInApartment: true,
    goodInHouse: true,
    goodInGarden: false,
    energyLevel: "low",
    adoptionFee: "0.00",
    imageUrl: "https://images.unsplash.com/photo-1595433707802-6b2626ef1c91?w=800",
  },
  {
    associationId: "seed_assoc_mx",
    animalType: "dog",
    name: "Luna",
    description:
      "Luna es una perra adulta de 6 anos, muy bien entrenada y protectora, ideal para casa con patio.",
    city: "Ciudad de Mexico",
    state: "CDMX",
    country: "MX",
    latitude: 19.44,
    longitude: -99.12,
    breed: "Ovejero Aleman Mix",
    sex: "female",
    ageGroup: "adult",
    size: "large",
    coatLength: "medium",
    coatColorPrimary: "brown",
    temperamentTags: ["protective", "trained", "calm"],
    goodWithKids: true,
    goodWithDogs: true,
    goodWithCats: false,
    goodInApartment: false,
    goodInHouse: true,
    goodInGarden: true,
    energyLevel: "medium",
    adoptionFee: "0.00",
    imageUrl: "https://images.unsplash.com/photo-1561037404-61cd46aa615b?w=800",
  },

  // ---- Spain (Adopta un Amigo, Madrid) ----
  {
    associationId: "seed_assoc_es",
    animalType: "dog",
    name: "Rocky",
    description:
      "Rocky es un perro adulto de 3 anos, muy jugueton y sociable, le encantan los parques.",
    city: "Madrid",
    state: "Madrid",
    country: "ES",
    latitude: 40.4168,
    longitude: -3.7038,
    breed: "Podenco Mix",
    sex: "male",
    ageGroup: "adult",
    size: "medium",
    coatLength: "short",
    coatColorPrimary: "brown",
    temperamentTags: ["playful", "sociable", "energetic"],
    goodWithKids: true,
    goodWithDogs: true,
    goodWithCats: false,
    goodInApartment: true,
    goodInHouse: true,
    goodInGarden: true,
    energyLevel: "high",
    adoptionFee: "80.00",
    imageUrl: "https://images.unsplash.com/photo-1552053831-71594a27632d?w=800",
  },
  {
    associationId: "seed_assoc_es",
    animalType: "cat",
    name: "Mia",
    description:
      "Mia es una gata joven de 1 ano, curiosa y carinosa, se lleva bien con otros gatos.",
    city: "Madrid",
    state: "Madrid",
    country: "ES",
    latitude: 40.42,
    longitude: -3.71,
    breed: "European Shorthair",
    sex: "female",
    ageGroup: "young",
    size: "small",
    coatLength: "short",
    coatColorPrimary: "gray",
    temperamentTags: ["curious", "affectionate", "playful"],
    goodWithKids: true,
    goodWithDogs: false,
    goodWithCats: true,
    goodInApartment: true,
    goodInHouse: true,
    goodInGarden: false,
    energyLevel: "medium",
    adoptionFee: "60.00",
    imageUrl: "https://images.unsplash.com/photo-1513360371669-4adf3dd7dff8?w=800",
  },
  {
    associationId: "seed_assoc_es",
    animalType: "dog",
    name: "Nala",
    description:
      "Nala es una cachorra de 5 meses, muy energica, ideal para una familia activa con ninos.",
    city: "Barcelona",
    state: "Cataluna",
    country: "ES",
    latitude: 41.3874,
    longitude: 2.1686,
    breed: "Mixed Breed",
    sex: "female",
    ageGroup: "puppy/kitten",
    size: "small",
    coatLength: "medium",
    coatColorPrimary: "cream",
    temperamentTags: ["energetic", "affectionate", "playful"],
    goodWithKids: true,
    goodWithDogs: true,
    goodWithCats: true,
    goodInApartment: true,
    goodInHouse: true,
    goodInGarden: false,
    energyLevel: "high",
    adoptionFee: "80.00",
    imageUrl: "https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=800",
  },
  {
    associationId: "seed_assoc_es",
    animalType: "cat",
    name: "Simba",
    description:
      "Simba es un gato senior de 10 anos, tranquilo y muy carinoso, busca un hogar sin prisas.",
    city: "Madrid",
    state: "Madrid",
    country: "ES",
    latitude: 40.41,
    longitude: -3.69,
    breed: "Domestic Shorthair",
    sex: "male",
    ageGroup: "senior",
    size: "medium",
    coatLength: "short",
    coatColorPrimary: "orange",
    temperamentTags: ["calm", "affectionate", "gentle"],
    goodWithKids: true,
    goodWithDogs: false,
    goodWithCats: true,
    goodInApartment: true,
    goodInHouse: true,
    goodInGarden: false,
    energyLevel: "low",
    adoptionFee: "40.00",
    imageUrl: "https://images.unsplash.com/photo-1478098711619-5ab0b478d6e6?w=800",
  },
  {
    associationId: "seed_assoc_es",
    animalType: "dog",
    name: "Trufa",
    description:
      "Trufa es una perra adulta de 5 anos, calmada y bien entrenada, perfecta para un piso en la ciudad.",
    city: "Madrid",
    state: "Madrid",
    country: "ES",
    latitude: 40.43,
    longitude: -3.68,
    breed: "Galgo Mix",
    sex: "female",
    ageGroup: "adult",
    size: "large",
    coatLength: "short",
    coatColorPrimary: "gray",
    temperamentTags: ["calm", "trained", "gentle"],
    goodWithKids: true,
    goodWithDogs: true,
    goodWithCats: true,
    goodInApartment: true,
    goodInHouse: true,
    goodInGarden: false,
    energyLevel: "low",
    adoptionFee: "70.00",
    imageUrl: "https://images.unsplash.com/photo-1518717758536-85ae29035b6d?w=800",
  },

  // ---- Canada (Northern Paws Rescue, Toronto) ----
  {
    associationId: "seed_assoc_ca",
    animalType: "dog",
    name: "Maple",
    description:
      "Maple is a friendly 2-year-old Husky mix who loves cold weather and long runs.",
    city: "Toronto",
    state: "Ontario",
    country: "CA",
    latitude: 43.6532,
    longitude: -79.3832,
    breed: "Husky Mix",
    sex: "female",
    ageGroup: "young",
    size: "large",
    coatLength: "long",
    coatColorPrimary: "gray",
    temperamentTags: ["friendly", "energetic", "loyal"],
    goodWithKids: true,
    goodWithDogs: true,
    goodWithCats: false,
    goodInApartment: false,
    goodInHouse: true,
    goodInGarden: true,
    energyLevel: "high",
    adoptionFee: "200.00",
    imageUrl: "https://images.unsplash.com/photo-1517849845537-4d257902861a?w=800",
  },
  {
    associationId: "seed_assoc_ca",
    animalType: "cat",
    name: "Willow",
    description:
      "Willow is a gentle 3-year-old tabby who enjoys quiet afternoons and window watching.",
    city: "Toronto",
    state: "Ontario",
    country: "CA",
    latitude: 43.65,
    longitude: -79.38,
    breed: "Domestic Shorthair",
    sex: "female",
    ageGroup: "adult",
    size: "medium",
    coatLength: "short",
    coatColorPrimary: "brown",
    temperamentTags: ["gentle", "quiet", "affectionate"],
    goodWithKids: true,
    goodWithDogs: false,
    goodWithCats: true,
    goodInApartment: true,
    goodInHouse: true,
    goodInGarden: false,
    energyLevel: "low",
    adoptionFee: "150.00",
    imageUrl: "https://images.unsplash.com/photo-1533738363-b7f9aef128ce?w=800",
  },
  {
    associationId: "seed_assoc_ca",
    animalType: "dog",
    name: "Bear",
    description:
      "Bear is a 6-month-old puppy full of energy, still learning basic commands but eager to please.",
    city: "Ottawa",
    state: "Ontario",
    country: "CA",
    latitude: 45.4215,
    longitude: -75.6972,
    breed: "Mixed Breed",
    sex: "male",
    ageGroup: "puppy/kitten",
    size: "medium",
    coatLength: "medium",
    coatColorPrimary: "black",
    temperamentTags: ["energetic", "playful", "eager"],
    goodWithKids: true,
    goodWithDogs: true,
    goodWithCats: true,
    goodInApartment: false,
    goodInHouse: true,
    goodInGarden: true,
    energyLevel: "high",
    adoptionFee: "220.00",
    imageUrl: "https://images.unsplash.com/photo-1543852786-1cf6624b9987?w=800",
  },
  {
    associationId: "seed_assoc_ca",
    animalType: "cat",
    name: "Oliver",
    description:
      "Oliver is a senior 9-year-old cat, calm and dignified, looking for a peaceful retirement home.",
    city: "Toronto",
    state: "Ontario",
    country: "CA",
    latitude: 43.66,
    longitude: -79.39,
    breed: "British Shorthair",
    sex: "male",
    ageGroup: "senior",
    size: "medium",
    coatLength: "short",
    coatColorPrimary: "gray",
    temperamentTags: ["calm", "dignified", "affectionate"],
    goodWithKids: true,
    goodWithDogs: false,
    goodWithCats: true,
    goodInApartment: true,
    goodInHouse: true,
    goodInGarden: false,
    energyLevel: "low",
    adoptionFee: "100.00",
    imageUrl: "https://images.unsplash.com/photo-1595433707802-6b2626ef1c91?w=800",
  },
  {
    associationId: "seed_assoc_ca",
    animalType: "dog",
    name: "Daisy",
    description:
      "Daisy is a 4-year-old adult dog, calm and well-mannered, great with kids and other pets.",
    city: "Toronto",
    state: "Ontario",
    country: "CA",
    latitude: 43.64,
    longitude: -79.37,
    breed: "Golden Retriever Mix",
    sex: "female",
    ageGroup: "adult",
    size: "large",
    coatLength: "long",
    coatColorPrimary: "golden",
    temperamentTags: ["calm", "friendly", "gentle"],
    goodWithKids: true,
    goodWithDogs: true,
    goodWithCats: true,
    goodInApartment: false,
    goodInHouse: true,
    goodInGarden: true,
    energyLevel: "medium",
    adoptionFee: "180.00",
    imageUrl: "https://images.unsplash.com/photo-1552053831-71594a27632d?w=800",
  },
];
